appdjango1/urls.py
from django.urls import path
from . import views

app_name ='appdjango1'
urlpatterns = [    
    path('list',views.list_view, name='list_view'),
    path('login',views.login, name='login'),
    path('chat/<str:room_name>/', views.room, name='room'),
    path('chat', views.chat, name='chat'),
    path('<id>', views.detail_view),
    path('<id>/update', views.update_view),
    path('<id>/delete', views.delete_view),
]

djangoexo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('appdjango1/', include('appdjango1.urls')),
    path('admin/', admin.site.urls),
]

appdjango1/models.py
from django.db import models

class Question(models.Model):
    titre = models.CharField(max_length = 200)
    lienimage = models.CharField(max_length=500)
    description = models.TextField()
    prix = models.DecimalField(max_digits=20, decimal_places=2)
    quantite = models.IntegerField()
    
    def __str__(self):
        return self.titre

appdjango1/forms.py
from django import forms
from .models import Question
 
 
# creating a form
class Appform(forms.ModelForm):
 
    # create meta class
    class Meta:
        # specify model to be used
        model = Question
 
        # specify fields to be used
        fields = [
            "titre","prix","quantite","lienimage","description",
        ]


class Achatform(forms.ModelForm):
 
    # create meta class
    class Meta:
        # specify model to be used
        model = Question
 
        # specify fields to be used
        fields = [
            "quantite",
        ]

appdjango1/views.py
from multiprocessing import context
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, response, Http404, HttpResponseRedirect

from .models import Question
from .forms import Appform
from .forms import Achatform
from django.utils import timezone

from django.shortcuts import render


def index(request):

    return render(request,'appdjango1/index.html')


def list_view(request):
    # dictionary for initial data with
    # field names as keys
    context ={}
 
    # add the dictionary during initialization
    context["dataset"] = Question.objects.all()
    form = Appform(request.POST or None)
    if form.is_valid():
        form.save()

        return HttpResponseRedirect("/appdjango1/list")
         
    context['form']= form
         
    return render(request, "appdjango1/list_view.html", context)


def detail_view(request, id):
    # dictionary for initial data with
    # field names as keys
    context ={}
    
 
    # add the dictionary during initialization
    context["data"] = Question.objects.get(id = id)

    obj = get_object_or_404(Question, id = id)
    quantite_stock = obj.quantite

    form = Achatform(request.POST or None, instance = obj)
    if form.is_valid():
        quantite_achat = obj.quantite
        stock_restant = quantite_stock-quantite_achat
        obj.quantite = stock_restant
        form.save()

        return HttpResponseRedirect("/appdjango1/list")
         
    context['form']= form

         
    return render(request, "appdjango1/detail_view.html", context)

 
# update view for details
def update_view(request, id):
    # dictionary for initial data with
    # field names as keys
    context ={}
 
    # fetch the object related to passed id
    obj = get_object_or_404(Question, id = id)
 
    # pass the object as instance in form
    form = Appform(request.POST or None, instance = obj)
 
    # save the data from the form and
    # redirect to detail_view
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/appdjango1/"+id)
 
    # add form dictionary to context
    context["form"] = form
 
    return render(request, "appdjango1/update_view.html", context)


def delete_view(request, id):
    # dictionary for initial data with
    # field names as keys
    context ={}
 
    # fetch the object related to passed id
    obj = get_object_or_404(Question, id = id)
 
 
    if request.method =="POST":
        # delete object
        obj.delete()
        # after deleting redirect to
        # home page
        return HttpResponseRedirect("/appdjango1/list")
 
    return render(request, "appdjango1/delete_view.html", context)


def login(request):
    context ={}

    login = "user"
    mdp = "1234"

    form = Appform(request.POST or None)
    if form.is_valid():
        #if login = True :
            #if mdp = True :
                #acceder à la page list

        form.save()
        return HttpResponseRedirect("/appdjango1/list")


    return render(request, "appdjango1/login.html", context)



def chat(request):

    return render(request, 'appdjango1/chat.html')

def room(request, room_name):
    return render(request, 'appdjango1/room.html', {
        'room_name': room_name
    })

appdjango1/templates/appdjango1/chat.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/appdjango1/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

appdjango1/templates/appdjango1/create_view.html
<form method="POST" enctype="multipart/form-data">
 
    <!-- Security token -->
    {% csrf_token %}
 
    <!-- Using the formset -->
    {{ form.as_p }}
     
    <input type="submit" value="Submit">
</form>

appdjango1/templates/appdjango1/delete_view.html
<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        Êtes vous sûr de vouloir supprimer cet article ?
        <input type="submit" value="Oui" />
        <a href="/appdjango1/list">Non retourner à la boutique</a>
    </form>
</div>

appdjango1/templates/appdjango1/detail_view.html
{% load static %}
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>Titre de la page</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <header>
    <div><img src="{% static 'img/logo_django.png' %}" alt="logo"></div>
    <div><a href="chat/discussion/"> CHAT</a> <a href="login"> LOGIN</a></div>
  </header>
  
  <div class="main_achat">
      
    <div class="detail_produit">

      <!-- Specify fields to be displayed -->
      <div><img src="{{ data.lienimage }}"></div>

      <div>
        <span style="font-size : 30px; font-weight:bold;">{{ data.titre }}</span>
        <span style="font-size: 12px;">{{ data.description }}</span>
        <span style="font-size: 20px;font-weight: bold;">{{ data.prix }}€</span>
        <span style="font-size: 12px;">Stock : {{ data.quantite }}</span>

        <form method="POST" enctype="multipart/form-data">
            <!-- Security token -->
            {% csrf_token %}
          
            <!-- Using the formset -->
            <!--  {{ form.as_p }}-->
            <input id="id_quantite" type="number" name="quantite" min="1" max="{{ data.quantite }}">
            <input type="submit" value="Achetez">
        </form>
      </div>

    </div>

    <div class="action_produit">
      <button onclick="window.location.href = '{{data.id}}/update';">Modifier</button>
      <button onclick="window.location.href = '{{data.id}}/delete';">Supprimer</button>
      <button onclick="window.location.href = 'list';">Retour à la liste</button>
    </div>

  </div>
<body>
</html>

appdjango1/templates/appdjango1/list_view.html
{% load static %}
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>Titre de la page</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <header>
    <div><img src="{% static 'img/logo_django.png' %}" alt="logo"></div>
    <div><a href="chat/discussion/"> CHAT</a> <a href="login"> LOGIN</a></div>
  </header>
  <div class="main">
    <h1>Boutique</h1>
    <div class="boutique">
      {% for data in dataset %}

      {% if data.quantite > 0 %}
      <div class="produit">
        <div><img src="{{ data.lienimage }}"></div>
        <div>
          <span style="font-weight:bold;">{{ data.titre }}</span>
          <span style="font-size: 12px;">{{ data.description }}</span>
          <span style="font-size: 20px;font-weight: bold;">{{ data.prix }}€</span>
          <span style="font-size: 12px;">Stock : {{ data.quantite }}</span></div>
        <div>
        <button onclick="window.location.href = '{{data.id}}';"> Voir détail</button></div>
      </div>

      {% endif %}

      {% endfor %}

    </div>

    <div class="create_objet">
      <h1>Ajouter un article</h1>
      <form method="POST" enctype="multipart/form-data">

        <!-- Security token -->
        {% csrf_token %}
      
        <!-- Using the formset -->
        {{ form.as_p }}
          
        <input type="submit" value="Ajouter">
      </form>
    </div>
  </div>
</body>
</html>

appdjango1/templates/appdjango1/login.html
{% load static %}
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>Titre de la page</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <header>
    <div><img src="{% static 'img/logo_django.png' %}" alt="logo"></div>
    <div><a href="chat/discussion/"> CHAT</a></div>
  </header>
  <div class="main">
    <form method="post"  role="form" action="/">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Utilisateur">
        <input type="password" name="password" placeholder="Mot de passe">
        <input type="submit" value="login" />
    </form>
  </div>
</body>
</html>

appdjango1/templates/appdjango1/room.html
<!-- chat/templates/chat/room.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Envoyer">
    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>

appdjango1/templates/appdjango1/update_view.html
<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
 
        <!-- form as paragraph -->
        {{ form.as_p }}
 
        <input type="submit" value="Update">
    </form>
 
</div>